### ISSUE TITLE
are there any papers related to the library?

### ISSUE THREAD

**Issue by qcl1994** [rpng/calc#1]

**Comment by ghuangud** [comment]
Yes, the paper will be presented at this year RSS.

**Comment by qcl1994** [comment]
Has it been published online？

**Comment by nmerrill67** [comment]
Not yet. It will be released along with the other RSS2018 papers, and we will link to it in this repo once that happens.

**Comment by nmerrill67** [comment]
Please see http://arxiv.org/abs/1805.07703
