### ISSUE TITLE
deep model in SLAM

### ISSUE THREAD

**Issue by zqnnn** [rpng/calc#10]
Hey, are you try to use calc model to detect loops in SLAM system? How can we combine the deep model and whole slam system?

**Comment by nmerrill67** [comment]
Yes. You can get an idea of how to integrate CALC into a SLAM system from the online demo, where ground truth replaces the trajectory estimation. CALC essentially gives you what DBoW2 gives you (in terms of implementation). You can perform k-nearest neighbor searches for key frames, and find loop closure candidates using some thresholding of the similarity scores.

**Comment by goldbattle** [comment]
Here is a youtube video showing what Nate is referencing:
https://www.youtube.com/watch?v=Bmg03-QtynY
