### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by thornsu** [rpng/calc#11]
Hello, thank you for your research. When I build DeepLCD, I get this error:
haosu@haosu-B85-HD3:~/LCD/calc/DeepLCD/build$ make
[  5%] Performing update step for 'googletest'
当前分支 master 是最新的。
[ 11%] Performing configure step for 'googletest'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/haosu/LCD/calc/DeepLCD/build/src/googletest-build
[ 16%] Performing build step for 'googletest'
[ 25%] Built target gtest
[ 50%] Built target gmock
[ 75%] Built target gmock_main
[100%] Built target gtest_main
[ 22%] No install step for 'googletest'
[ 27%] Completed 'googletest'
[ 44%] Built target googletest
[ 55%] Built target deeplcd
[ 66%] Built target demo
make[2]: *** No rule to make target 'src/googletest-build/googlemock/gtest/libgtest.a', needed by 'deeplcd-test'。 停止。
CMakeFiles/Makefile2:211: recipe for target 'CMakeFiles/deeplcd-test.dir/all' failed
make[1]: *** [CMakeFiles/deeplcd-test.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
I use cuda 8.0 and https://github.com/BVLC/caffe , can you help me?

**Comment by nmerrill67** [comment]
It looks to me like you did not install gtest static libraries correctly. Please refer to to the gtest documentation to see how to build and/or install it statically. However, if you do not want to build unit tests please just compile with -DBUILD_TESTS=OFF to avoid linking to gtest altogether by not compiling unit tests.

**Comment by thornsu** [comment]
thank you！
