### ISSUE TITLE
from pydbow2 import pyDBoW2，: cannot import name pyDBoW2

### ISSUE THREAD

**Issue by UestcVan** [rpng/calc#12]
When I compiled and build DBOW2, I want to do from pydbow2 import pyDBoW2,Console display cannot import name pyDBoW2, how I to dealwith it.

**Comment by nmerrill67** [comment]
You need to add the binary directory to your path. An example of this is [here](https://github.com/rpng/calc/blob/master/TrainAndTest/testNet.py#L124). I believe you can also do it by adding to your PYTHONPATH environment variable.

**Comment by UestcVan** [comment]
hi,I have solved this problem,Thanks
