### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by cyc790** [rpng/calc#16]
When I make the DeepLCD code, errors occur as the follow:

[ 50%] Building CXX object CMakeFiles/deeplcd.dir/src/deeplcd/deeplcd.cpp.o
In file included from /home/cyc/caffe/build/install/include/caffe/blob.hpp:9:0,
                 from /home/cyc/caffe/build/install/include/caffe/caffe.hpp:7,
                 from /home/cyc/calc-master/DeepLCD/include/deeplcd/deeplcd.h:1,
                 from /home/cyc/calc-master/DeepLCD/src/deeplcd/deeplcd.cpp:1:
/home/cyc/caffe/build/install/include/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/cyc/caffe/build/install/include/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/cyc/caffe/build/install/include/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/cyc/caffe/build/install/include/caffe/blob.hpp:9:0,
                 from /home/cyc/caffe/build/install/include/caffe/caffe.hpp:7,
                 from /home/cyc/calc-master/DeepLCD/include/deeplcd/deeplcd.h:1,
                 from /home/cyc/calc-master/DeepLCD/src/deeplcd/deeplcd.cpp:1:
/home/cyc/caffe/build/install/include/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: no such file or directory
compilation terminated.
CMakeFiles/deeplcd.dir/build.make:62: recipe for target 'CMakeFiles/deeplcd.dir/src/deeplcd/deeplcd.cpp.o' failed
make[2]: *** [CMakeFiles/deeplcd.dir/src/deeplcd/deeplcd.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/deeplcd.dir/all' failed
make[1]: *** [CMakeFiles/deeplcd.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

how to solve it?

**Comment by nmerrill67** [comment]
Have you by any chance upgraded your protobuf version since installing Caffe? I would try to recompile Caffe if so. Let me know if this is not the case.
