### ISSUE TITLE
implementation about the LA model

### ISSUE THREAD

**Issue by qcl1994** [rpng/calc#17]
Hi, nate. Do you have the open source code for the model created by Lopez-Antequera ?

**Comment by nmerrill67** [comment]
I have the model, but it is not exactly open-sourced since the authors did not ever provide a link. Instead I emailed the authors to get the model, so I should not share it without their permission. If you email them I am sure they will send it.

**Comment by qcl1994** [comment]
Thanks for your reply! Could you tell me how to test the model on the kitti 00?

**Comment by nmerrill67** [comment]
You will have to change the code in `DeepLCD` to reflect the output blob from their model.
