### ISSUE TITLE
what is the dataset you use in the ros online demo

### ISSUE THREAD

**Issue by zqnnn** [rpng/calc#2]
what is the pos_topic

**Comment by nmerrill67** [comment]
Good question. I made a custom publisher for KITTI data. There is a python script that does it [here](https://github.com/nmerrill67/kitti_publisher). The EuRO MAV datasets also work out of the box with that demo, and I also have [another python script](https://github.com/nmerrill67/new_college_publisher) to publish the New College Dataset in the right format. The online demo needs an Image topic as well as a topic with trajectories either as a TransformStamped or PoseStamped topic.

**Comment by zqnnn** [comment]
Thanks! Another question,please. What is the training dataset used by the calc caffemodel?

**Comment by nmerrill67** [comment]
We use the MIT Places dataset. Please see http://arxiv.org/abs/1805.07703
