### ISSUE TITLE
compile DBoW2 error

### ISSUE THREAD

**Issue by JinghuiChan** [rpng/calc#21]
Hi Nate
    When I compiled DBoW2, I got the following error:
   calc/TrainAndTest/ThirdParty/DBoW2/src/pywrap.cpp:125:17: error: ‘boost::python::numeric’ has not been declared
  boost::python::numeric::array::set_module_and_type("numpy", "ndarray");

 How should I solve it?
![Screenshot from 2019-09-15 18-44-38](https://user-images.githubusercontent.com/39593077/64920325-f0921200-d7e8-11e9-9249-87d21e35d542.png)

**Comment by nmerrill67** [comment]
Mine compiles just fine (just checked). My boost version is 1.58.0 and python is 2.7.12.
Make sure you have `libboost-python1.58-dev` installed.

**Comment by JinghuiChan** [comment]
Thank you, after the boost version was changed, the compilation was successful.
