### ISSUE TITLE
What is the value of loss?

### ISSUE THREAD

**Issue by wangtiandong-roborock** [rpng/calc#26]
Hi @nmerrill67 ,
I'm finetuing calc network on our own dataset. Could you provide the final value of your training loss? Mine is 63, which I think is too large, and the PR Curve is also worse than your weights.
I trained the network 500k iterations.

**Comment by shenyanqing1105** [comment]
> Hi @nmerrill67 ,
> I'm finetuing calc network on our own dataset. Could you provide the final value of your training loss? Mine is 63, which I think is too large, and the PR Curve is also worse than your weights.
> I trained the network 500k iterations.

Excuse me, have you solved this problem? I have a similar problem now

**Comment by wangtiandong-roborock** [comment]
> > Hi @nmerrill67 ,
> > I'm finetuing calc network on our own dataset. Could you provide the final value of your training loss? Mine is 63, which I think is too large, and the PR Curve is also worse than your weights.
> > I trained the network 500k iterations.
> 
> Excuse me, have you solved this problem? I have a similar problem now

No, I haven't. I found there were lots of other methods better than calc network. I do suggest you read more recent papers.

**Comment by shenyanqing1105** [comment]
> > > Hi @nmerrill67 ,
> > > I'm finetuing calc network on our own dataset. Could you provide the final value of your training loss? Mine is 63, which I think is too large, and the PR Curve is also worse than your weights.
> > > I trained the network 500k iterations.
> > 
> > 
> > Excuse me, have you solved this problem? I have a similar problem now
> 
> No, I haven't. I found there were lots of other methods better than calc network. I do suggest you read more recent papers.

Got it! Thanks for your suggestion~
