### ISSUE TITLE
When I execute cmake .. && make in the build folder of DeepLCD I get the following error

### ISSUE THREAD

**Issue by MareSorin-Alexandru** [rpng/calc#28]
I installed everything laid out in the DeepLCD README.md and even tried installing gtest manually, but this persists.

![image](https://user-images.githubusercontent.com/47454888/92137515-1dc63e80-ee05-11ea-94ad-f716753d9ad3.png)

**Comment by nmerrill67** [comment]
It seems that you are not building it from within the build directory. This could at least explain the `cp` errors. You should run `cmake ..` from within `DeepLCD/build`.

**Comment by MareSorin-Alexandru** [comment]
My bad, it seems I have uploaded the wrong Screenshot.
Thank you for pointing out my mistake @nmerrill67 .

I think this was from a time I ran "cmake . && make" in the Deep LCD folder itself.

If I try to run the original command "cmake .. && make" in the DeepLCD folder I get the following message;
![image](https://user-images.githubusercontent.com/47454888/92139433-a219c100-ee07-11ea-9dbd-46ff3e7caa67.png)

This is a screenshot of the actual issue, 
![image](https://user-images.githubusercontent.com/47454888/92138838-d345c180-ee06-11ea-9962-b502be07b1cb.png)

**Comment by nmerrill67** [comment]
Do you have git installed? It seems like that is (one of) the error(s) there.
