### ISSUE TITLE
 Cannot use GPU in CPU-only Caffe: check mode. *** Check failure stack trace: ***

### ISSUE THREAD

**Issue by irobotDavinci** [rpng/calc#7]
Hi,
   Just  I want to test Calc, I type this cmd:
python main.py test
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0719 15:04:57.433012 24072 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Did I operated wrong ? Any Help,Thanks

**Comment by irobotDavinci** [comment]
Ops

**Comment by chenjiangtao229** [comment]
Hello, now I have also encountered this problem, how did you solve it then?
